server:
  port: 9014
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka
spring:
  application:
    name: turbine
  kafka:
    bootstrap-servers: localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: "*"
