eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
  tomcat:
    max-connections: 2
    max-threads: 2
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
zuul:
  prefix: /api
  strip-prefix: false
  sensitive-headers:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ec
    api-b:
      path: /api-b/**
      serviceId: ec2
    api-c:
      path: /api-c/**
      serviceId: user
